---
- hosts: local
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.micro
    security_group: webservers_sg
    image: ami-0080e4c5bc078760e
    keypair: subash
    region: us-east-1
    count: 1
  vars_files:
    - aws_keys.yml

  tasks:
    - name: Create Launch Configuration
      ec2_lc:
        region: "{{ region }}"
        name: "webapp"
        image_id: "{{ image }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        security_groups: "{{ security_group }}"
        volumes: "{{ volumes }}"
        instance_monitoring: yes
      register: lc_result  
        
    - name: Create ASG
      ec2_asg:
        name: "wepapp_asg"
     #   load_balancers: [ 'lb1', 'lb2' ]
        availability_zones: [ 'us-east-1d', 'us-east-1b' ]
        launch_config_name: "{{ lc_result.name }}"
        min_size: 1
        max_size: 2
        desired_capacity: 1
        state: present
        vpc_zone_identifier: [ 'subnet-170d265d', 'subnet-2cfc674b' ]
        health_check_type: EC2
        health_check_period: 300
        tags:
          - environment: production
     #       propagate_at_launch: no
      register: asg_result
